
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mvp
  template:
    metadata:
      labels:
        app: mvp
    spec:
      containers:
      - name: mvp-container
        image: mvp-dashboard:latest
        ports:
        - containerPort: 5000
